artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts\data_ingestion
  source_URL: https://github.com/TechGovinda/Datasets/raw/main/Chicken-fecal-images.zip
  local_data_file: data.zip
  unzip_dir: artifacts\extreacted_repo